name: signal-desktop
title: Signal Desktop
summary: Speak Freely - Private Messenger
description: |
  **Note: To use the Signal desktop app, you must first install Signal on your phone.**

  Millions of people use Signal every day for free and instantaneous communication anywhere in the world. Send and receive high-fidelity messages, participate in HD voice/video calls, and explore a growing set of new features that help you stay connected. Signal's advanced privacy-preserving technology is always enabled, so you can focus on sharing the moments that matter with the people who matter to you.

  - Say anything - State-of-the-art end-to-end encryption (powered by the open source Signal Protocol™) keeps your conversations secure. Privacy isn't an optional mode; it's just the way that Signal works. Every message, every call, every time.
  - Go fast - Messages are delivered quickly and reliably, even on slow networks. Signal is optimized to operate in the most constrained environment possible.
  - Feel free - Signal is a completely independent 501c3 nonprofit. Development is supported by users like you. No advertisements. No trackers. No kidding.
  - Be yourself - You can use your existing phone number and address book to securely communicate with your friends.
  - Speak up - Whether they live across town or across the ocean, Signal's enhanced audio and video quality will make your friends and family feel closer.
  - Whisper in the shadows - Switch to the dark theme if you refuse to see the light.

  **Minimize to tray**

  Per the request of the Signal developers, this snap does not use the system tray by default. This is disabled by default per the request of the Signal developers, because system tray support is not stable. Set to `false`, Signal will stop when you close it and will not have a system tray icon. You can enable it by running the following command.

      snap set signal-desktop tray-icon=true


  **Are you having issues?**

  Let us know by creating a new issue here: https://github.com/snapcrafters/signal-desktop/issues

  **Authors**

  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.
website: https://signal.org/
contact: https://github.com//snapcrafters/signal-desktop/issues
issues: https://github.com//snapcrafters/signal-desktop/issues
source-code: https://github.com//snapcrafters/signal-desktop
license: AGPL-3.0-only
adopt-info: signal-desktop
icon: snap/gui/signal-desktop.png
version: 8.8.0

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64:

parts:
  signal-desktop:
    plugin: dump
    source: https://github.com/signalapp/Signal-Desktop
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - curl
      - execstack
      - git-lfs
      - jq
      - moreutils
      - python3
    build-environment:
      - SIGNAL_ENV: "production"
      - ELECTRON_GET_USE_PROXY: "1"
    override-build: |
      # Install pnpm and the correct version of nodejs
      curl -fsSL https://get.pnpm.io/install.sh | env SHELL=bash sh -
      export PATH="/root/.local/share/pnpm:$PATH"
      export PNPM_HOME="/root/.local/share/pnpm"
      pnpm env use --global "$(jq -r .engines.node package.json)"

      git lfs install

      # Build the sticker-creator
      pnpm -C ./sticker-creator/ install
      pnpm -C ./sticker-creator/ run build

      # Add a patch that fixes the rendering of images on arm64 builds.
      # See: https://github.com/snapcrafters/signal-desktop/issues/279#issuecomment-2372021170
      cp $CRAFT_PROJECT_DIR/snap/patches/* patches/

      # Apply patches
      cat package.json | jq -r --arg fs_extra patches/fs-extra+11.2.0.patch '.pnpm.patchedDependencies."fs-extra"=$fs_extra ' | sponge package.json
      patch -p1 <patches/production-desktop-name.patch

      # Install the dependencies for the Signal-Desktop application.
      pnpm install
      pnpm run generate
       
      # This is the equivalent of 'npm run build-linux' with some adjustments
      pnpm run build:esbuild:prod
      pnpm run build:electron --config.directories.output=release --dir

      # Stage the built release. Directory is called 'linux-unpacked' for amd64,
      # and 'linux-arm64-unpacked' for arm64.
      mkdir -p "${CRAFT_PART_INSTALL}/opt"
      mv release/linux-*unpacked "${CRAFT_PART_INSTALL}/opt/Signal"
    stage-packages:
      - libnss3
      - libnss-sss
      # Needed for non-gpu accelerated workaround in wrapper script.
      # See: https://github.com/electron/electron/issues/48321
      - mesa-utils
    prime:
      - -opt/Signal/chrome-sandbox
      - -opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  local-parts:
    plugin: dump
    source: ./snap/local
    source-type: local

  # Needed because mesa-utils pulls in mesa libraries that conflict with the gpu-2404 interface
  gpu-2404:
    after:
      - signal-desktop
      - local-parts
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404

apps:
  signal-desktop:
    extensions: [gnome]
    command: usr/bin/signal-desktop-wrapper
    plugs:
      - browser-support
      - camera
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
      - unity7
      - screen-inhibit-control
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
