name: signal-desktop
title: Signal Desktop
summary: Private messaging from your desktop.
description: |
  Private messaging from your desktop.
  
  To use the Signal desktop app, Signal must first be installed on your phone.

  **Are you having issues?**

  Let us know by creating a new issue here: https://github.com/snapcrafters/signal-desktop/issues

  **Authors**

  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.
license: AGPL-3.0-only
adopt-info: signal-desktop
icon: snap/gui/signal-desktop.png
version: 6.7.0

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64
compression: lzo

parts:
  signal-desktop:
    plugin: dump
    source: https://updates.signal.org/desktop/apt/pool/main/s/signal-desktop/signal-desktop_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    stage-packages:
      - libxss1
      - libnspr4
      - libnss3
      - libvips42
    prime:
      - opt
      - usr/share
      - usr/lib/*/libxss*
      - usr/lib/*/*nss*
      - usr/lib/*/libvips*
      - usr/lib/*/libI*
      - usr/lib/*/libMagic*
      - usr/lib/*/libcfit*
      - usr/lib/*/libcgif*
      - usr/lib/*/libexif*
      - usr/lib/*/libfftw*
      - usr/lib/*/libgsf*
      - usr/lib/*/libheif*
      - usr/lib/*/libimage*
      - usr/lib/*/libmat*
      - usr/lib/*/libopensli*
      - usr/lib/*/libwebp*
      - usr/lib/*/libHalf*
      - usr/lib/*/libaom*
      - usr/lib/*/libdav1d*
      - usr/lib/*/libx265*
      - usr/lib/*/libhdf*
      - usr/lib/*/libsz*
      - usr/lib/*/liblqr*
      - usr/lib/*/libaec*
      - usr/lib/*/libde265*
      - usr/lib/*/libnuma*
      - -opt/Signal/chrome-sandbox
      - -opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  cleanup:
    after: [signal-desktop]
    plugin: nil
    build-snaps: [gnome-42-2204]
    override-prime: |
      set -eux
      cd /snap/gnome-42-2204/current
      find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;
      for CRUFT in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$CRUFT
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete

apps:
  signal-desktop:
    extensions: [gnome]
    desktop: usr/share/applications/signal-desktop.desktop
    command: opt/Signal/signal-desktop --use-tray-icon --no-sandbox
    plugs:
      - browser-support
      - camera
      - home
      - network
      - opengl
      - audio-playback
      - audio-record
      - removable-media
      - unity7
      - desktop
      - desktop-legacy
      - screen-inhibit-control
    environment:
      GTK_USE_PORTAL: "1"
      TMPDIR: $XDG_RUNTIME_DIR
